name: Build and Push

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_BASE_NAME: guss-alberto/unitntgbot-

jobs:
  build_push_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate bake definition from compose
        run: |
          docker buildx bake --print > docker-bake.json

      - name: Rewrite image targets to ghcr
        id: bakepatch
        run: |
          jq --arg registry "$REGISTRY" --arg image_base_name "$IMAGE_BASE_NAME" '
            .target |= with_entries(
              .value += {
                "tags": [
                  "\($registry)/\($image_base_name)\(.value.args.PACKAGE):latest"
                ]
              }
            )
          ' docker-bake.json > docker-bake-ghcr.json

      - name: Build and push
        id: docker_build
        uses: docker/bake-action@v6
        with:
          source: .
          files: docker-bake-ghcr.json
          push: true
